# Only for local development with postgres and docker
services:
  db:
    image: 'postgres:14.19-alpine3.21'
    container_name: db
    environment:
      - POSTGRES_DB=webtech_database
      - POSTGRES_USER=webtech_user
      - POSTGRES_PASSWORD=webtech_password
    ports:
      - "5432:5432"